<a href="https://colab.research.google.com/github/Enevales/Python_ML/blob/main/Python_Practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
Обработка данных.

"""

import numpy as np 
import sklearn.preprocessing as skp
input_data = np.array([[2.1, -1.9, 5.5],
                      [-1.5, 2.4, 3.5], 
                      [0.5, -7.9, 5.6], 
                      [5.9, 2.3, -5.8]])
# бинаризация данных
data_bin = skp.Binarizer(threshold=0.5).transform(input_data) 
print("Обработанные данные:", data_bin)


print("Cреднее значение каждого столбца = ", input_data.mean(axis = 0)) 
print("Cреднее значение каждой строки = ", input_data.mean(axis = 1)) 
print("Cреднеквадратическое отклонение каждого столбца = ", input_data.std(axis = 0)) 

# cтандартизация данных
data_scaled = skp.scale(input_data)
print("Среднее значение =", data_scaled.mean(axis=0)) 
print("Среднеквадратическое отклонение =", data_scaled.std(axis = 0))

# масштабирование данных 
data_scaler_minmax = skp.MinMaxScaler(feature_range=(0,1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data) 
print ("\nМасштабированные данные:\n", data_scaled_minmax)

# L1 нормализация (Метод наименьших модулей)
data_normalized_l1 = skp.normalize(input_data, norm = 'l1')
print("\nL1 нормализованные данные:\n", data_normalized_l1)

# L2 нормализация (Метод наименьших квадратов)
data_normalized_l2 = skp.normalize(input_data, norm = 'l2')
print("\nL2 нормализованные данные:\n", data_normalized_l2)

# -----------------------------------------------------------

Обработанные данные: [[1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]
 [1. 1. 0.]]
Cреднее значение каждого столбца =  [ 1.75  -1.275  2.2  ]
Cреднее значение каждой строки =  [ 1.9         1.46666667 -0.6         0.8       ]
Cреднеквадратическое отклонение каждого столбца =  [2.71431391 4.20022321 4.69414529]
Среднее значение = [1.11022302e-16 0.00000000e+00 0.00000000e+00]
Среднеквадратическое отклонение = [1. 1. 1.]

Масштабированные данные:
 [[0.48648649 0.58252427 0.99122807]
 [0.         1.         0.81578947]
 [0.27027027 0.         1.        ]
 [1.         0.99029126 0.        ]]

L1 нормализованные данные:
 [[ 0.22105263 -0.2         0.57894737]
 [-0.2027027   0.32432432  0.47297297]
 [ 0.03571429 -0.56428571  0.4       ]
 [ 0.42142857  0.16428571 -0.41428571]]

L2 нормализованные данные:
 [[ 0.33946114 -0.30713151  0.88906489]
 [-0.33325106  0.53320169  0.7775858 ]
 [ 0.05156558 -0.81473612  0.57753446]
 [ 0.68706914  0.26784051 -0.6754239 ]]


In [ ]:
"""
Кодирование данных.

"""

input_labels = ['Эрвин','Рудольф','Йозеф','Александр','Шрёдингер']
encoder = skp.LabelEncoder()
encoder.fit(input_labels)
LabelEncoder()

test_labels = ['Эрвин','Рудольф','Йозеф']
encoded_values = encoder.transform(test_labels)
print("Метки =", test_labels)
Labels = ['Эрвин','Рудольф','Йозеф']
print("Кодированные метки =", list(encoded_values))
decoded_list = encoder.inverse_transform(encoded_values)
print("Деодированные метки =", decoded_list)



Метки = ['Эрвин', 'Рудольф', 'Йозеф']
Кодированные метки = [4, 2, 1]
Кодированные метки = ['Эрвин' 'Рудольф' 'Йозеф']
